version: "3.7"
services:
  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: mysql
    volumes:
      - ./db/mysql:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    build:
      context: .
      dockerfile: ./db/Dockerfile

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - .:/api
      - /api/db
